runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: home.app

env_variables:
    CLOUDSQL_CONNECTION_NAME: kyc-scraping:us-central1:kyc-scraping-db
    CLOUDSQL_USER: maddie
    CLOUDSQL_PASSWORD: exostfp
# [END env_variables]